# Generated by Django 4.0.1 on 2022-01-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='usr',
            field=models.TextField(),
        ),
    ]
